- name: configure backend server
  become: yes
  hosts: backend
  vars:

  tasks:
  - name: disable default node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs:20
    ansible.builtin.dnf: #RHEL 
      name: nodejs
      state: installed

  - name: useradd expense
    ansible.builtin.user:
      name: expense

  - name: create app dire
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download backend code
    ansible.builtin.get_url: 
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: npm dependencies
    andible.builtin.command: npm install
    args:
      chdir: /app      








