- name: mysql
  hosts: db
  become: yes 
  vars:
    login_host: db.narendra.shop
  vars_prompt:
    name: mysql_root_password
    prompt: "Pls enter db password:::"
    private: no
  tasks:
  - name: db 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python mysql depenencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9    



  - name: mysql info
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
      filter: version   
    ignore_errors: yes 
    register: mysql_connection_output

  - name: print connection output
    ansible.builtin.debug:
      msg: "{{mysql_connection_output}}"
  - name: mysql connection
    ansible.builtin.command:  mysql_secure_installation --set-root-pass {{mysql_root_password}}
    when:   mysql_connection_output.failed is true 

