- name: install nginx
  hosts: frontend
  become: yes
  tasks: dnf install nginx -y 
  - name: insstall nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
      enabled: yes

  - name: rm -rf /usr/share/nginx/html/*
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent


