- name: install nginx
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes    



  - name: rm -rf /usr/share/nginx/html/*
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create /usr/share/nginx/html/*
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory     

  # - name: download backend code
  #   ansible.builtin.get_url: 
  #     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
  #     dest: /tmp/frontend.zip
 
  - name: unzip 
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes






